### ISSUE TITLE
Consolidate options into one option value

### ISSUE THREAD

**Issue by danielbachhuber** [JDowdNBC/nbcs-wp-moderation-queue-alerts#2]
Rather than have three different option rows, you can easily consolidate this into one option like 'nbcs-moderation' and store the plugin options in an array.

```
$options = get_option( 'nbcs-moderation' );
$queue_email = $options['queue-email'];
```

**Comment by JDowdNBC** [comment]
I can see how to retrieve the options, but I don't know how to set them as an associative array.  Currently I'm using register_setting(), and I couldn't find anything in the documentation about storing those settings as anything but individual options.

**Comment by danielbachhuber** [comment]
You'd just use register_setting() once, and then each of your fields would have a namespace like this:

`<input name="nbcs-moderation[queue-minimum]" id="queue-minimum">`

You'd create a validation callback that would process an array of values.
